config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'homes#top'
  # ルートパスでtop画面へ遷移できるように設定
  
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    # s複数形にしない。単数にするとコントローラーのidがリクエストに含まれなくなる
    # 今回の場合詳細ページが要らないため
    resources :post_comments, only: [:create, :destroy]
  # 不要なルーティングが実行されないようにonlyを設定
  # post_imagesの中にpost_comments,親子関係
  end
  resources:users,only:[:show,:edit,:update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end


# deviseのコントローラは、ライブラリで用意されているため、直接修正できない。
# deviseのコントローラに修正が必要なときは、application_controllerに記述が必要。

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

belongs_to :user
attachment :image # ここを追加（_idは含めません）refileを使用するにはattachmentメソッドを追加する必要がある
has_many :post_comments, dependent: :destroy
has_many :favorites, dependent: :destroy

validates :shop_name, presence: true
validates :image, presence: true
# データが入っていればtrue,入っていなければfalseが返される

def favorited_by?(user)
    # いいねしたユーザーのidと照らし合わせて、仮の変数のようなものを置いて定義
    favorites.where(user_id: user.id).exists?
    # モデル名.where("条件") 
    # Postimage.favorites = テーブル これをfavoritesだけで記載している、has_many :favoritesで定義しているので
end
# favorited_by?メソッドを作成。引数で渡されたユーザidが
# Favoritesテーブル内に存在（exists?）するかどうかを調べる
# true falseで返す
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # deviseの後ろに :（コロン）で始まる部分がdeviseの機能名
  # :database_authenticatable（パスワードの正確性を検証）
  # :registerable（ユーザ登録や編集、削除）
  # :recoverable（パスワードをリセット）
  # :rememberable（ログイン情報を保存）
  # :validatable（emailのフォーマットなどのバリデーション）
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  # attachment メソッドの引数に与える名前はカラム名からidを取ったもの
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  # 全てのコントローラーでアクション実行前に行われる
  # authenticate_userメソッドは、devise側が用意しているメソッド
  # :authenticate_user!とすることによって、「ログイン認証されていなければ、ログイン画面へリダイレクトする」機能を実装
  # exceptは指定したアクションをbefore_actionの対象から外す。今回の場合homes#top。
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  # （ユーザ登録、ログイン認証など）が使われる場合、その前にconfigure_permitted_parametersが実行される
  # devise_controller?とはdeviseを生成した際にできるヘルパーメソッドの一つ、deviseにまつわる画面に行った時に、
  # という意味,こうすることで全ての画面でconfigure_permitted_parametersが起動
  # devise_controller?というメソッドの返り値がtrueだったら、configure_permitted_parametersを呼ぶ
  
  def after_sign_in_path_for(resource)
    post_images_path
  end
  # Deviseでユーザーログイン後のリダイレクト先を変更
  
  protected
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
  # configure_permitted_parametersでは、devise_parameter_sanitizer.permitでnameのデータ操作を許可するアクションメソッドが指定。
  # 今回のケースでは、ユーザ登録（sign_up）の際に、ユーザ名（name）のデータ操作が許可される。
  # CARAVAN作成時のStrong Parametersと同様の機能。privateは、自分のコントローラ内でしか参照できない。

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  # configure_permitted_parametersはdevise版のストロングパラメーター
  # deviseでは初期設定でメールアドレスとパスワードしか許されていない
  # ここを編集することでユーザーネームなどを入れることができる
  # 今回の例だとnameカラムへの保存を許可する
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])

    # favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.post_image_id = post_image.id
    # 3行目で取ってきているpost_image

    favorite.save
    redirect_to post_image_path(post_image)

  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  # def before_commit
  # end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    # comment = current_user.post_comments.new(post_comment_params)
    # 上記は以下と同義。これわからんw
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    # id: params[:id] = post_commentのidを調べている。
    # route = post_images/:post_image_id/post_comments/:id(.:format) 
    redirect_to post_image_path(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
    # permitは保存・更新したい内容についてフィルターする
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
    # インスタンス変数に空のインスタンスを渡す
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    # この行で@post_image変数にuserテーブルのidを紐付かせている
    if @post_image.save
    # 投稿データを保存するアクションメソッド(POST)
      redirect_to post_images_path
    else
      render :new
      # render :アクション名で、同じコントローラ内の別アクションのViewを表示できる
    end
    # 投稿データを保存するには、Strong Parametersも必要
  end

  def index
    # @post_images = PostImage.all
    @post_images = PostImage.page(params[:page]).reverse_order
    # 1ページ分の決められた数のデータだけを、新しい順に取得
    # ページに表示させる件数の設定は、config/initializersのkaminari_config.rbファイルに記述
  end

  def show
    @post_image = PostImage.find(params[:id])
    # (params[:id])　はUrlのidを取ってきているイメージ
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end
  
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
    # フォームで入力されたデータが投稿データとして許可されているパラメータかどうかをチェック
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
    # ページメソッドでページを取ってくる
    
    # kaminariを導入すると、モデルクラスにpageメソッドが定義される。
    # このメソッドは、ページネーションにおけるページ数を指定。
    # ビューのリクエストの際paramsの中にpageというキーが追加されて、
    # その値がビューで指定したページ番号となる。pageの引数はparams[:page]となる。
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <!--ナビゲーションバーの表示,navbar-expand-[ブレークポイント],navbar-[カラースキーム]-->
        <!--この3つはセットで使用すると覚える-->
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <!--navbar-brand=ロゴに使用されるnavbarのサポートclass-->
          <!--p-[サイズ]=paddingの指定-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <!--navbar-toggler=ナビゲーションアイコン（ハンバーガーメニュー）の枠部分-->
          <!--ナビゲーションアイコンを開く前に隠しておきたいメニューは「collapse」classが付与された要素の中に入れておく-->
          <!--data-toggle="collapse"、data-target="#[id名]"は必ず指定しなければ、ナビゲーションアイコンの開閉を行うことができない-->
            <span class="navbar-toggler-icon"></span>
            <!--navbar-toggler-icon=ナビゲーションアイコン（ハンバーガーメニュー）の三本線部分-->
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <!--devise側で用意しているヘルパー-->
            <!--sign in時に出るリンク集-->
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <!--sign inしていない画面で出るリンク集-->
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
  
</html>

app/views/post_images/_list.html.erb
<div class="card-list-containar py-5">
  <% post_images.each do |post_image| %>
  <!--@post_image => post_imageへ変更（インスタンス変数=>ローカル変数へ）-->
  
  
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <!--w-50=with50%, mx-auto=左右のマージンをauto, mt-4=上側のマージンを1.5rem, shadow-lg=影（濃い）-->
    <!--よく使うクラスまとめ：https://qiita.com/nakanishi03/items/c80a16b9b9796c25f890-->
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, class:"card-img-top"; %>
      <!--attachment_image_tagは、refile側が用意したヘルパーで、imgタグを作成してくれる-->
      <!--post_image変数のimage_idに保存された画像のimgタグを生成する-->
      <!--link_toのdoとendで囲むことでattachment_image_tagはaタグに囲まれたことになりimgにリンクをつけれる-->
    <% end %>
    
    <div class="card-body">
      <!--カードのコンテンツ部分をcard-bodyで括る-->
      <div class="row">
        <div class="col-2">
          <!--2対10の割合で領域をグリッドにより分けている-->
          <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
          <!--mage_tag(source)メソッドでassets/imagesディレクトリに配置した画像をタグで呼び出せる-->
          <%#= attachment_image_tag 保存先インスタンス名, :保存先カラム名, :サイズ（横幅,高さ）, 画像拡張子, 代替画像 %>
        </div>
        <div class="col-10">
          <!--2対10の割合で領域をグリッドにより分けている-->
          <p class="card-title">
            <!--コンテンツ内のカード部分のタイトル名,shop nameがタイトル部分-->
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <!--コンテンツ内の説明部分-->
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <!--post_image変数のuser_idに紐づく名前を抽出してきている-->
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
          <!--imageにネストされたcommnets内のcomment-->
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
  <!--ページングのpageメソッドを利用して、すべての投稿画像が表示されないように設定-->
</div>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
<div>
  <%= link_to post_image_path(post_image.id) do %>
  <%= attachment_image_tag post_image, :image %>
  <!--attachment_image_tagは、refile側が用意したヘルパーで、imgタグを作成してくれる-->
  <!--post_image変数のimage_idに保存された画像のimgタグを生成する-->
  <% end %>
  
  <p>投稿ユーザー画像：<%= image_tag('sample-author1.jpg') %></p>
  <!--mage_tag(source)メソッドでassets/imagesディレクトリに配置した画像をタグで呼び出せる-->
  <p>ショップ名：<%= post_image.shop_name %></p>
  <p>説明：<%= post_image.caption %></p>
  <p>ユーザーネーム：<%= post_image.user.name %></p>
  <p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>
  <!--imageにネストされたcommnets内のcomment-->
</div>
<% end %>
<%= paginate @post_images %>
<!--kaminariを利用するためにヘルパーを追加-->

app/views/post_images/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <!--mx-2=左右のマージンを0.5rem(全て(≥0px), mx-sm-auto=左右のマージンauto(小以上(≥576px), shadow-lg=影（濃い）, -->
      <!--rounded=すべて角丸, px-0=左右のパディングを0(全て(≥0px), my-5=上下のマージンを3rem(全て(≥0px)-->
      <!--col-sm-10=画面幅が576px以上のときに12分割したグリッドの10分割分の幅をとる※このときの10分割分の幅は親要素であるrowの幅に依存-->
      <!--col-sm-10=画面幅が768px以上のときに12分割したグリッドの5分割分の幅をとる※このときの10分割分の幅は親要素であるrowの幅に依存-->
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
        <!--errorsはモデルにバリデーションをかけたときに、発生したエラーの内容を確認できるメソッド-->
        <!--any?と組み合わせることで、エラーが発生しているかどうかを判定できる-->
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local:true do |f| %>
        <!--form_withはrails 5.1以上-->
          <%= f.attachment_field :image, class: "w-100" %>
            <!--refileの文法の決まりで_idは要らない決まり-->
            <!--指定するフィールド名は、image_idから_idを除いた名前（image）を指定-->
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
            <!--カラムにユーザーが入れるものを保存するイメージ-->
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="post-body">
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <!--strftimeメソッド('%Y/%m/%d')、 '%Y/%m/%d'の記述で、年/月/日のフォーマットへ変換-->
  <% if @post_image.user == current_user %>
  <!--post_imageでcreate時に取ってきたUserテーブルのuser_idがcurrent_userと同じだったら。という意味-->
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
  <!--もし、投稿者 == 現在ログインしているユーザ だったら-->
    <!--削除ボタン-->
  <!--終わり-->
</div>

<div class="comments">
<p>コメント件数：<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>
  <%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
   <!--attachment_image_tag 保存先インスタンス名, :保存先カラム名, :サイズ（横幅,高さ）, 画像拡張子, 代替画像-->
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <!--削除を表示-->
  <% if post_comment.user == current_user %>
  <div class="comment-delete">
    <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
  </div>
  <% end %>
<% end %>
  <!--favorite機能-->
  <% if @post_image.favorited_by?(current_user) %>
  <!--showアクションの変数が入ってくる、対応しているアクションの中身の変数しか使えない-->
  <!--アクション名とビューファイルは名前一致のものしか通信できない-->
  <!--モデル内で定義した自作のメソッドをここで使用-->
  <!--投稿画像に付けられた「いいね」に、自分（ログインしているユーザ）が含まれているか判定-->
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
      <!--deleteする時のview画面は♥なので、このように記載している。-->
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
  
</div>
<div class="new-comment">
<%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
<!--配列でインスタンス変数を2つ指定、コメントは、post_imageに結びついたネストさせているのでこのように書く（Rails決まり）-->
<!--post_commentはpost_imageあっての投稿なので、紐づいた変数用意が必要-->
<!--空だとPost,中身あるとPATCH-->
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <!--「autofocus: true」とはページを読み込んだらすぐにautofocus属性を-->
  <!--記述している部分カーソルが移動して入力状態になる-->

  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <!--attachment_image_tagは、refile側が用意したヘルパーで、画像を埋め込むときに使う-->
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <!--attachment_fieldで、画像選択用のボタンが生成され-->
  <!--profile_imageはuserモデルからの引数-->

  <%= f.submit "変更を保存" %>
  
<% end %>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <%#= attachment_image_tag 保存先インスタンス名, :保存先カラム名, :サイズ（横幅,高さ）, 画像拡張子, 代替画像 %>
  
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>
<%= render 'post_images/list', post_images: @post_images %>
<!--部分テンプレートを呼び出せるよう設定-->

<%#= render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値] %>
<!--部分テンプレートファイルを呼び出すには、renderを使う-->
<!--'post_images/list'で部分テンプレートのパス（app/viewsより下のパス）を記述する-->
<!--その際、アンダースコアと拡張子は省略する(listでOK-->
<!--post_imagesは部分テンプレート内で使用する変数（＝ローカル変数）。-->
<!--@posts＿imagesは、postコントローラのindexアクションで定義した変数。-->
<!--つまり、部分テンプレート内でpostsを使用した場合、その変数の中身は、-->
<!--postコントローラのindexアクションで定義された@post_imagesと同義となる。-->